# Sprint S11 – Data Analytics with Pandas
## Level 1 – DataFrames & Selection
### Exercise 1 – Introduction to DataFrames
A DataFrame is a 2D table with rows and columns — like an Excel sheet or SQL table.

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("financials_clean.csv")
df.head()

In [1]:
import pandas as pd
df = pd.read_csv("financials.csv")

df.head()

,Country,Año,Trimestre,Mes,Día,Month Name,Product,Segment,Suma de Sales,Avg Sale per Unit,...,Suma de Gross Sales,Suma de Manufacturing Price,Suma de Month Number,Suma de Profit,Profit Margin %,Suma de Sale Price,Total COGS,Suma de Units Sold,Suma de Year,Discount Band
0,Canada,2013,Qtr 3,septiembre,1,September,Amarilla,Channel Partners,29156.16,"10,56 €",...,33132.0,260,9,20873.16,71.590909,12,8283 €,2761,2013,High
1,Canada,2013,Qtr 3,septiembre,1,September,Carretera,Enterprise,265760.00,110 €,...,302000.0,3,9,-24160.00,-9.090909,125,289920 €,2416,2013,High
2,Canada,2013,Qtr 3,septiembre,1,September,Montana,Small Business,354108.00,276 €,...,384900.0,5,9,33358.00,9.420290,300,320750 €,1283,2013,Medium
3,Canada,2013,Qtr 3,septiembre,1,September,Paseo,Government,15620.85,"6,65 €",...,16443.0,10,9,3875.85,24.812030,7,11745 €,2349,2013,Medium
4,Canada,2013,Qtr 3,septiembre,1,September,Paseo,Midmarket,31863.00,"12,9 €",...,37050.0,10,9,7163.00,22.480620,15,24700 €,2470,2013,High

In [2]:
print("Shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

Shape: (688, 22)

Column names:
['Country', 'Año', 'Trimestre', 'Mes', 'Día', 'Month Name', 'Product', 'Segment', 'Suma de  Sales', 'Avg Sale per Unit', 'Suma de COGS', 'Suma de Discounts', 'Suma de Gross Sales', 'Suma de Manufacturing Price', 'Suma de Month Number', 'Suma de Profit', 'Profit Margin %', 'Suma de Sale Price', 'Total COGS', 'Suma de Units Sold', 'Suma de Year', 'Discount Band']

In [4]:
df = df.rename(columns={
    'Año': 'Year',
    'Trimestre': 'Quarter',
    'Mes': 'Month',
    'Día': 'Day',
    'Suma de  Sales': 'Sales',
    'Suma de COGS': 'COGS',
    'Suma de Discounts': 'Discounts',
    'Suma de Gross Sales': 'Gross Sales',
    'Suma de Manufacturing Price': 'Manufacturing Price',
    'Suma de Month Number': 'Month Number',
    'Suma de Profit': 'Profit',
    'Suma de Sale Price': 'Sale Price',
    'Suma de Units Sold': 'Units Sold',
    'Suma de Year': 'Year2'
})

In [5]:
df.head()

,Country,Year,Quarter,Month,Day,Month Name,Product,Segment,Sales,Avg Sale per Unit,...,Gross Sales,Manufacturing Price,Month Number,Profit,Profit Margin %,Sale Price,Total COGS,Units Sold,Year2,Discount Band
0,Canada,2013,Qtr 3,septiembre,1,September,Amarilla,Channel Partners,29156.16,"10,56 €",...,33132.0,260,9,20873.16,71.590909,12,8283 €,2761,2013,High
1,Canada,2013,Qtr 3,septiembre,1,September,Carretera,Enterprise,265760.00,110 €,...,302000.0,3,9,-24160.00,-9.090909,125,289920 €,2416,2013,High
2,Canada,2013,Qtr 3,septiembre,1,September,Montana,Small Business,354108.00,276 €,...,384900.0,5,9,33358.00,9.420290,300,320750 €,1283,2013,Medium
3,Canada,2013,Qtr 3,septiembre,1,September,Paseo,Government,15620.85,"6,65 €",...,16443.0,10,9,3875.85,24.812030,7,11745 €,2349,2013,Medium
4,Canada,2013,Qtr 3,septiembre,1,September,Paseo,Midmarket,31863.00,"12,9 €",...,37050.0,10,9,7163.00,22.480620,15,24700 €,2470,2013,High

In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv("financials.csv")

In [9]:
df.columns

Index(['Country', 'Year', 'Quarter', 'Month', 'Day', 'Month Name', 'Product',
       'Segment', 'Sales', 'Avg Sale per Unit', 'COGS', 'Discounts',
       'Gross Sales', 'Manufacturing Price', 'Month Number', 'Profit',
       'Profit Margin %', 'Sale Price', 'Total COGS', 'Units Sold', 'Year2',
       'Discount Band'],
      dtype='str')

In [12]:
df.iloc[0] # primeira linha

Country                          Canada
Year                               2013
Quarter                           Qtr 3
Month                        septiembre
Day                                   1
Month Name                    September
Product                        Amarilla
Segment                Channel Partners
Sales                          29156.16
Avg Sale per Unit               10,56 €
COGS                             8283.0
Discounts                       3975.84
Gross Sales                     33132.0
Manufacturing Price                 260
Month Number                          9
Profit                         20873.16
Profit Margin %               71.590909
Sale Price                           12
Total COGS                       8283 €
Units Sold                         2761
Year2                              2013
Discount Band                      High
Name: 0, dtype: object

In [13]:
df.iloc[0:5] # primeiras 5 linhas

,Country,Year,Quarter,Month,Day,Month Name,Product,Segment,Sales,Avg Sale per Unit,...,Gross Sales,Manufacturing Price,Month Number,Profit,Profit Margin %,Sale Price,Total COGS,Units Sold,Year2,Discount Band
0,Canada,2013,Qtr 3,septiembre,1,September,Amarilla,Channel Partners,29156.16,"10,56 €",...,33132.0,260,9,20873.16,71.590909,12,8283 €,2761,2013,High
1,Canada,2013,Qtr 3,septiembre,1,September,Carretera,Enterprise,265760.00,110 €,...,302000.0,3,9,-24160.00,-9.090909,125,289920 €,2416,2013,High
2,Canada,2013,Qtr 3,septiembre,1,September,Montana,Small Business,354108.00,276 €,...,384900.0,5,9,33358.00,9.420290,300,320750 €,1283,2013,Medium
3,Canada,2013,Qtr 3,septiembre,1,September,Paseo,Government,15620.85,"6,65 €",...,16443.0,10,9,3875.85,24.812030,7,11745 €,2349,2013,Medium
4,Canada,2013,Qtr 3,septiembre,1,September,Paseo,Midmarket,31863.00,"12,9 €",...,37050.0,10,9,7163.00,22.480620,15,24700 €,2470,2013,High

In [14]:
df.iloc[:, 0]   # primeira coluna

0                        Canada
1                        Canada
2                        Canada
3                        Canada
4                        Canada
                 ...
683    United States of America
684    United States of America
685    United States of America
686    United States of America
687    United States of America
Name: Country, Length: 688, dtype: str

In [15]:
df.head()

,Country,Year,Quarter,Month,Day,Month Name,Product,Segment,Sales,Avg Sale per Unit,...,Gross Sales,Manufacturing Price,Month Number,Profit,Profit Margin %,Sale Price,Total COGS,Units Sold,Year2,Discount Band
0,Canada,2013,Qtr 3,septiembre,1,September,Amarilla,Channel Partners,29156.16,"10,56 €",...,33132.0,260,9,20873.16,71.590909,12,8283 €,2761,2013,High
1,Canada,2013,Qtr 3,septiembre,1,September,Carretera,Enterprise,265760.00,110 €,...,302000.0,3,9,-24160.00,-9.090909,125,289920 €,2416,2013,High
2,Canada,2013,Qtr 3,septiembre,1,September,Montana,Small Business,354108.00,276 €,...,384900.0,5,9,33358.00,9.420290,300,320750 €,1283,2013,Medium
3,Canada,2013,Qtr 3,septiembre,1,September,Paseo,Government,15620.85,"6,65 €",...,16443.0,10,9,3875.85,24.812030,7,11745 €,2349,2013,Medium
4,Canada,2013,Qtr 3,septiembre,1,September,Paseo,Midmarket,31863.00,"12,9 €",...,37050.0,10,9,7163.00,22.480620,15,24700 €,2470,2013,High

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 688 entries, 0 to 687
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Country              688 non-null    str
 1   Year                 688 non-null    int64
 2   Quarter              688 non-null    str
 3   Month                688 non-null    str
 4   Day                  688 non-null    int64
 5   Month Name           688 non-null    str
 6   Product              688 non-null    str
 7   Segment              688 non-null    str
 8   Sales                688 non-null    float64
 9   Avg Sale per Unit    688 non-null    str
 10  COGS                 688 non-null    float64
 11  Discounts            688 non-null    float64
 12  Gross Sales          688 non-null    float64
 13  Manufacturing Price  688 non-null    int64
 14  Month Number         688 non-null    int64
 15  Profit               688 non-null    float64
 16  Profit Margin %      688 non-null    float64
 17  Sale Price           688 non-null    int64
 18  Total COGS           688 non-null    str
 19  Units Sold           688 non-null    int64
 20  Year2                688 non-null    int64
 21  Discount Band        635 non-null    str
dtypes: float64(6), int64(7), str(9)
memory usage: 118.4 KB

In [17]:
df.describe()

,Year,Day,Sales,COGS,Discounts,Gross Sales,Manufacturing Price,Month Number,Profit,Profit Margin %,Sale Price,Units Sold,Year2
count,688.000000,688.0,6.880000e+02,688.000000,688.000000,6.880000e+02,688.000000,688.000000,688.000000,688.000000,688.000000,688.000000,688.000000
mean,2013.752907,1.0,1.725674e+05,148012.569767,13379.721279,1.859471e+05,98.159884,8.037791,24554.799797,27.920749,120.494186,1636.345930,2048.873547
std,0.431635,0.0,2.378659e+05,204813.857573,23104.288235,2.554770e+05,114.143226,3.716876,43075.622538,23.557468,137.247277,886.873167,263.769385
min,2013.000000,1.0,1.655080e+03,918.000000,0.000000,1.799000e+03,3.000000,1.000000,-40617.500000,-12.941176,7.000000,200.000000,2013.000000
25%,2014.000000,1.0,1.650857e+04,7851.750000,820.225000,1.771875e+04,5.000000,5.000000,2948.097500,12.523957,12.000000,913.500000,2014.000000
50%,2014.000000,1.0,3.705000e+04,24642.500000,2763.800000,3.947000e+04,10.000000,9.000000,9395.200000,23.371648,20.000000,1568.000000,2014.000000
75%,2014.000000,1.0,2.635119e+05,248422.500000,16591.500000,2.897250e+05,250.000000,11.000000,23218.000000,43.181818,300.000000,2294.500000,2014.000000
max,2014.000000,1.0,1.159200e+06,950625.000000,149677.500000,1.207500e+06,520.000000,24.000000,262200.000000,75.000000,370.000000,4492.000000,4028.000000

In [18]:
df.shape

(688, 22)

In [19]:
df.columns

Index(['Country', 'Year', 'Quarter', 'Month', 'Day', 'Month Name', 'Product',
       'Segment', 'Sales', 'Avg Sale per Unit', 'COGS', 'Discounts',
       'Gross Sales', 'Manufacturing Price', 'Month Number', 'Profit',
       'Profit Margin %', 'Sale Price', 'Total COGS', 'Units Sold', 'Year2',
       'Discount Band'],
      dtype='str')

In [20]:
df.loc[:, "Country"]

0                        Canada
1                        Canada
2                        Canada
3                        Canada
4                        Canada
                 ...
683    United States of America
684    United States of America
685    United States of America
686    United States of America
687    United States of America
Name: Country, Length: 688, dtype: str

In [22]:
df.loc[df["Country"] == "United States of America"]

,Country,Year,Quarter,Month,Day,Month Name,Product,Segment,Sales,Avg Sale per Unit,...,Gross Sales,Manufacturing Price,Month Number,Profit,Profit Margin %,Sale Price,Total COGS,Units Sold,Year2,Discount Band
551,United States of America,2013,Qtr 3,septiembre,1,September,Amarilla,Channel Partners,23629.32,"11,88 €",...,23868.0,260,9,17662.32,74.747475,12,5967 €,1989,2013,Low
552,United States of America,2013,Qtr 3,septiembre,1,September,Carretera,Enterprise,40837.50,"123,75 €",...,41250.0,3,9,1237.50,3.030303,125,39600 €,330,2013,Low
553,United States of America,2013,Qtr 3,septiembre,1,September,Montana,Small Business,741906.00,297 €,...,749400.0,5,9,117406.00,15.824916,300,624500 €,2498,2013,Low
554,United States of America,2013,Qtr 3,septiembre,1,September,Paseo,Government,2367.40,"6,23 €",...,2660.0,10,9,467.40,19.743178,7,1900 €,380,2013,High
555,United States of America,2013,Qtr 3,septiembre,1,September,Paseo,Midmarket,40887.45,"13,95 €",...,43965.0,10,9,11577.45,28.315412,15,29310 €,2931,2013,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
683,United States of America,2014,Qtr 4,diciembre,1,December,Paseo,Government,92064.00,336 €,...,95900.0,10,12,20824.00,22.619048,350,71240 €,274,2014,Low
684,United States of America,2014,Qtr 4,diciembre,1,December,Paseo,Government,50597.00,19 €,...,53260.0,10,12,23967.00,47.368421,20,26630 €,2663,2014,Medium
685,United States of America,2014,Qtr 4,diciembre,1,December,Velo,Channel Partners,9322.80,"10,2 €",...,10968.0,120,12,6580.80,70.588235,12,2742 €,914,2014,High
686,United States of America,2014,Qtr 4,diciembre,1,December,Velo,Small Business,382788.00,279 €,...,411600.0,120,12,39788.00,10.394265,300,343000 €,1372,2014,Medium
687,United States of America,2014,Qtr 4,diciembre,1,December,VTT,Government,54387.50,"16,8226 €",...,57250.0,500,24,24907.50,45.796369,27,29480 €,3233,4028,Medium

In [23]:
df[(df["Country"] == "France") & (df["Sales"] > 1000)]

,Country,Year,Quarter,Month,Day,Month Name,Product,Segment,Sales,Avg Sale per Unit,...,Gross Sales,Manufacturing Price,Month Number,Profit,Profit Margin %,Sale Price,Total COGS,Units Sold,Year2,Discount Band
137,France,2013,Qtr 3,septiembre,1,September,Carretera,Enterprise,109972.50,"107,5 €",...,127875.0,3,9,-12787.50,-11.627907,125,122760 €,1023,2013,High
138,France,2013,Qtr 3,septiembre,1,September,Montana,Small Business,87906.00,273 €,...,96600.0,5,9,7406.00,8.424908,300,80500 €,322,2013,Medium
139,France,2013,Qtr 3,septiembre,1,September,Paseo,Government,6711.81,"6,51 €",...,7217.0,10,9,1556.81,23.195084,7,5155 €,1031,2013,Medium
140,France,2013,Qtr 3,septiembre,1,September,Paseo,Midmarket,8235.00,15 €,...,8235.0,10,9,2745.00,33.333333,15,5490 €,549,2013,NaN
141,France,2013,Qtr 3,septiembre,1,September,Velo,Government,49929.00,"17,8 €",...,56100.0,120,9,21879.00,43.820225,20,28050 €,2805,2013,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,France,2014,Qtr 4,diciembre,1,December,Paseo,Government,746707.50,"346,5 €",...,754250.0,10,12,186407.50,24.963925,350,560300 €,2155,2014,Low
271,France,2014,Qtr 4,diciembre,1,December,Velo,Channel Partners,12406.80,"11,76 €",...,12660.0,120,12,9241.80,74.489796,12,3165 €,1055,2014,Low
272,France,2014,Qtr 4,diciembre,1,December,Velo,Small Business,230310.00,270 €,...,255900.0,120,12,17060.00,7.407407,300,213250 €,853,2014,High
273,France,2014,Qtr 4,diciembre,1,December,VTT,Government,4981.00,17 €,...,5860.0,250,12,2051.00,41.176471,20,2930 €,293,2014,High
274,France,2014,Qtr 4,diciembre,1,December,VTT,Government,16538.55,"6,65 €",...,17409.0,250,12,4103.55,24.812030,7,12435 €,2487,2014,Medium

In [24]:
df[(df["Profit"] < 0) | (df["Profit Margin %"] < 0.1)]

,Country,Year,Quarter,Month,Day,Month Name,Product,Segment,Sales,Avg Sale per Unit,...,Gross Sales,Manufacturing Price,Month Number,Profit,Profit Margin %,Sale Price,Total COGS,Units Sold,Year2,Discount Band
1,Canada,2013,Qtr 3,septiembre,1,September,Carretera,Enterprise,265760.00,110 €,...,302000.0,3,9,-24160.00,-9.090909,125,289920 €,2416,2013,High
25,Canada,2013,Qtr 4,noviembre,1,November,VTT,Enterprise,313862.50,"106,25 €",...,369250.0,250,11,-40617.50,-12.941176,125,354480 €,2954,2013,High
32,Canada,2013,Qtr 4,diciembre,1,December,Velo,Enterprise,215550.00,"112,5 €",...,239500.0,120,12,-14370.00,-6.666667,125,229920 €,1916,2013,High
34,Canada,2014,Qtr 1,enero,1,January,Amarilla,Enterprise,180416.25,"108,75 €",...,207375.0,260,1,-18663.75,-10.344828,125,199080 €,1659,2014,High
46,Canada,2014,Qtr 1,febrero,1,February,Velo,Enterprise,111860.00,"117,5 €",...,119000.0,120,2,-2380.00,-2.127660,125,114240 €,952,2014,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
659,United States of America,2014,Qtr 4,octubre,1,October,Paseo,Enterprise,102243.75,"118,75 €",...,107625.0,10,10,-1076.25,-1.052632,125,103320 €,861,2014,Medium
662,United States of America,2014,Qtr 4,octubre,1,October,Velo,Enterprise,102243.75,"118,75 €",...,107625.0,120,10,-1076.25,-1.052632,125,103320 €,861,2014,Medium
674,United States of America,2014,Qtr 4,noviembre,1,November,VTT,Enterprise,262570.00,110 €,...,298375.0,250,11,-23870.00,-9.090909,125,286440 €,2387,2014,High
679,United States of America,2014,Qtr 4,diciembre,1,December,Montana,Enterprise,318158.75,"113,75 €",...,349625.0,5,12,-17481.25,-5.494505,125,335640 €,2797,2014,Medium
682,United States of America,2014,Qtr 4,diciembre,1,December,Paseo,Enterprise,318158.75,"113,75 €",...,349625.0,10,12,-17481.25,-5.494505,125,335640 €,2797,2014,Medium

In [25]:
df["Profit Check"] = df["Sales"] - df["COGS"]

In [27]:
df.head()

,Country,Year,Quarter,Month,Day,Month Name,Product,Segment,Sales,Avg Sale per Unit,...,Manufacturing Price,Month Number,Profit,Profit Margin %,Sale Price,Total COGS,Units Sold,Year2,Discount Band,Profit Check
0,Canada,2013,Qtr 3,septiembre,1,September,Amarilla,Channel Partners,29156.16,"10,56 €",...,260,9,20873.16,71.590909,12,8283 €,2761,2013,High,20873.16
1,Canada,2013,Qtr 3,septiembre,1,September,Carretera,Enterprise,265760.00,110 €,...,3,9,-24160.00,-9.090909,125,289920 €,2416,2013,High,-24160.00
2,Canada,2013,Qtr 3,septiembre,1,September,Montana,Small Business,354108.00,276 €,...,5,9,33358.00,9.420290,300,320750 €,1283,2013,Medium,33358.00
3,Canada,2013,Qtr 3,septiembre,1,September,Paseo,Government,15620.85,"6,65 €",...,10,9,3875.85,24.812030,7,11745 €,2349,2013,Medium,3875.85
4,Canada,2013,Qtr 3,septiembre,1,September,Paseo,Midmarket,31863.00,"12,9 €",...,10,9,7163.00,22.480620,15,24700 €,2470,2013,High,7163.00

In [28]:
df["Performance"] = np.where(
    df["Profit"] > 1000, "Excellent",
    np.where(df["Profit"] > 500, "Good", "Bad")
)

In [29]:
df.head()

,Country,Year,Quarter,Month,Day,Month Name,Product,Segment,Sales,Avg Sale per Unit,...,Month Number,Profit,Profit Margin %,Sale Price,Total COGS,Units Sold,Year2,Discount Band,Profit Check,Performance
0,Canada,2013,Qtr 3,septiembre,1,September,Amarilla,Channel Partners,29156.16,"10,56 €",...,9,20873.16,71.590909,12,8283 €,2761,2013,High,20873.16,Excellent
1,Canada,2013,Qtr 3,septiembre,1,September,Carretera,Enterprise,265760.00,110 €,...,9,-24160.00,-9.090909,125,289920 €,2416,2013,High,-24160.00,Bad
2,Canada,2013,Qtr 3,septiembre,1,September,Montana,Small Business,354108.00,276 €,...,9,33358.00,9.420290,300,320750 €,1283,2013,Medium,33358.00,Excellent
3,Canada,2013,Qtr 3,septiembre,1,September,Paseo,Government,15620.85,"6,65 €",...,9,3875.85,24.812030,7,11745 €,2349,2013,Medium,3875.85,Excellent
4,Canada,2013,Qtr 3,septiembre,1,September,Paseo,Midmarket,31863.00,"12,9 €",...,9,7163.00,22.480620,15,24700 €,2470,2013,High,7163.00,Excellent

In [29]:
df.head()

,Country,Year,Quarter,Month,Day,Month Name,Product,Segment,Sales,Avg Sale per Unit,...,Month Number,Profit,Profit Margin %,Sale Price,Total COGS,Units Sold,Year2,Discount Band,Profit Check,Performance
0,Canada,2013,Qtr 3,septiembre,1,September,Amarilla,Channel Partners,29156.16,"10,56 €",...,9,20873.16,71.590909,12,8283 €,2761,2013,High,20873.16,Excellent
1,Canada,2013,Qtr 3,septiembre,1,September,Carretera,Enterprise,265760.00,110 €,...,9,-24160.00,-9.090909,125,289920 €,2416,2013,High,-24160.00,Bad
2,Canada,2013,Qtr 3,septiembre,1,September,Montana,Small Business,354108.00,276 €,...,9,33358.00,9.420290,300,320750 €,1283,2013,Medium,33358.00,Excellent
3,Canada,2013,Qtr 3,septiembre,1,September,Paseo,Government,15620.85,"6,65 €",...,9,3875.85,24.812030,7,11745 €,2349,2013,Medium,3875.85,Excellent
4,Canada,2013,Qtr 3,septiembre,1,September,Paseo,Midmarket,31863.00,"12,9 €",...,9,7163.00,22.480620,15,24700 €,2470,2013,High,7163.00,Excellent

In [30]:
def classify_profit(x):
    if x > 1000:
        return "High"
    elif x > 500:
        return "Medium"
    else:
        return "Low"

df["Profit Class"] = df["Profit"].apply(classify_profit)

In [31]:
df.head()

,Country,Year,Quarter,Month,Day,Month Name,Product,Segment,Sales,Avg Sale per Unit,...,Profit,Profit Margin %,Sale Price,Total COGS,Units Sold,Year2,Discount Band,Profit Check,Performance,Profit Class
0,Canada,2013,Qtr 3,septiembre,1,September,Amarilla,Channel Partners,29156.16,"10,56 €",...,20873.16,71.590909,12,8283 €,2761,2013,High,20873.16,Excellent,High
1,Canada,2013,Qtr 3,septiembre,1,September,Carretera,Enterprise,265760.00,110 €,...,-24160.00,-9.090909,125,289920 €,2416,2013,High,-24160.00,Bad,Low
2,Canada,2013,Qtr 3,septiembre,1,September,Montana,Small Business,354108.00,276 €,...,33358.00,9.420290,300,320750 €,1283,2013,Medium,33358.00,Excellent,High
3,Canada,2013,Qtr 3,septiembre,1,September,Paseo,Government,15620.85,"6,65 €",...,3875.85,24.812030,7,11745 €,2349,2013,Medium,3875.85,Excellent,High
4,Canada,2013,Qtr 3,septiembre,1,September,Paseo,Midmarket,31863.00,"12,9 €",...,7163.00,22.480620,15,24700 €,2470,2013,High,7163.00,Excellent,High

In [32]:
df["Profit Bin"] = pd.cut(
    df["Profit"],
    bins=[-9999, 0, 500, 10000],
    labels=["Loss", "Medium", "High"]
)

In [33]:
df.head()

,Country,Year,Quarter,Month,Day,Month Name,Product,Segment,Sales,Avg Sale per Unit,...,Profit Margin %,Sale Price,Total COGS,Units Sold,Year2,Discount Band,Profit Check,Performance,Profit Class,Profit Bin
0,Canada,2013,Qtr 3,septiembre,1,September,Amarilla,Channel Partners,29156.16,"10,56 €",...,71.590909,12,8283 €,2761,2013,High,20873.16,Excellent,High,NaN
1,Canada,2013,Qtr 3,septiembre,1,September,Carretera,Enterprise,265760.00,110 €,...,-9.090909,125,289920 €,2416,2013,High,-24160.00,Bad,Low,NaN
2,Canada,2013,Qtr 3,septiembre,1,September,Montana,Small Business,354108.00,276 €,...,9.420290,300,320750 €,1283,2013,Medium,33358.00,Excellent,High,NaN
3,Canada,2013,Qtr 3,septiembre,1,September,Paseo,Government,15620.85,"6,65 €",...,24.812030,7,11745 €,2349,2013,Medium,3875.85,Excellent,High,High
4,Canada,2013,Qtr 3,septiembre,1,September,Paseo,Midmarket,31863.00,"12,9 €",...,22.480620,15,24700 €,2470,2013,High,7163.00,Excellent,High,High

In [34]:
df.loc[:, "Profit Bin"]

0       NaN
1       NaN
2       NaN
3      High
4      High
       ...
683     NaN
684     NaN
685    High
686     NaN
687     NaN
Name: Profit Bin, Length: 688, dtype: category
Categories (3, str): ['Loss' < 'Medium' < 'High']

In [35]:
df["Profit"].isnull().sum()

np.int64(0)

In [36]:
df["Profit"].describe()

count       688.000000
mean      24554.799797
std       43075.622538
min      -40617.500000
25%        2948.097500
50%        9395.200000
75%       23218.000000
max      262200.000000
Name: Profit, dtype: float64

In [37]:
df["Profit Bin"] = pd.qcut(
    df["Profit"],
    q=4,
    labels=["Low", "Medium", "High", "Very High"]
)

In [38]:
df.loc[:, "Profit Bin"]

0           High
1            Low
2      Very High
3         Medium
4         Medium
         ...
683         High
684    Very High
685       Medium
686    Very High
687    Very High
Name: Profit Bin, Length: 688, dtype: category
Categories (4, str): ['Low' < 'Medium' < 'High' < 'Very High']

In [39]:
df[df["Profit Bin"].isnull()]

Empty DataFrame
Columns: [Country, Year, Quarter, Month, Day, Month Name, Product, Segment, Sales, Avg Sale per Unit, COGS, Discounts, Gross Sales, Manufacturing Price, Month Number, Profit, Profit Margin %, Sale Price, Total COGS, Units Sold, Year2, Discount Band, Profit Check, Performance, Profit Class, Profit Bin]
Index: []

[0 rows x 26 columns]

In [40]:
df.to_csv("financials_clean.csv", index=False)

In [41]:
import os
print(os.getcwd())

C:\Users\apbal

In [42]:
df = df.drop(columns=["Month"])

In [43]:
df = df.drop(columns=["Year2"])

In [44]:
df.head()

,Country,Year,Quarter,Day,Month Name,Product,Segment,Sales,Avg Sale per Unit,COGS,...,Profit,Profit Margin %,Sale Price,Total COGS,Units Sold,Discount Band,Profit Check,Performance,Profit Class,Profit Bin
0,Canada,2013,Qtr 3,1,September,Amarilla,Channel Partners,29156.16,"10,56 €",8283.0,...,20873.16,71.590909,12,8283 €,2761,High,20873.16,Excellent,High,High
1,Canada,2013,Qtr 3,1,September,Carretera,Enterprise,265760.00,110 €,289920.0,...,-24160.00,-9.090909,125,289920 €,2416,High,-24160.00,Bad,Low,Low
2,Canada,2013,Qtr 3,1,September,Montana,Small Business,354108.00,276 €,320750.0,...,33358.00,9.420290,300,320750 €,1283,Medium,33358.00,Excellent,High,Very High
3,Canada,2013,Qtr 3,1,September,Paseo,Government,15620.85,"6,65 €",11745.0,...,3875.85,24.812030,7,11745 €,2349,Medium,3875.85,Excellent,High,Medium
4,Canada,2013,Qtr 3,1,September,Paseo,Midmarket,31863.00,"12,9 €",24700.0,...,7163.00,22.480620,15,24700 €,2470,High,7163.00,Excellent,High,Medium

In [45]:
df.to_csv("financials_clean.csv", index=False)

In [5]:
import os
print(os.getcwd())

C:\Users\apbal\python-portfolio-s11

In [6]:
import os
print(os.getcwd())

C:\Users\apbal\python-portfolio-s11

In [7]:
os.listdir()

['.ipynb_checkpoints',
 'financials_clean.csv',
 'nivel1_dataframes_selection.ipynb']

In [8]:
df = pd.read_csv("financials_clean.csv")

In [9]:
import pandas as pd
import numpy as np

df = pd.read_csv("financials_clean.csv")
df.head()

,Country,Year,Quarter,Day,Month Name,Product,Segment,Sales,Avg Sale per Unit,COGS,...,Profit,Profit Margin %,Sale Price,Total COGS,Units Sold,Discount Band,Profit Check,Performance,Profit Class,Profit Bin
0,Canada,2013,Qtr 3,1,September,Amarilla,Channel Partners,29156.16,"10,56 €",8283.0,...,20873.16,71.590909,12,8283 €,2761,High,20873.16,Excellent,High,High
1,Canada,2013,Qtr 3,1,September,Carretera,Enterprise,265760.00,110 €,289920.0,...,-24160.00,-9.090909,125,289920 €,2416,High,-24160.00,Bad,Low,Low
2,Canada,2013,Qtr 3,1,September,Montana,Small Business,354108.00,276 €,320750.0,...,33358.00,9.420290,300,320750 €,1283,Medium,33358.00,Excellent,High,Very High
3,Canada,2013,Qtr 3,1,September,Paseo,Government,15620.85,"6,65 €",11745.0,...,3875.85,24.812030,7,11745 €,2349,Medium,3875.85,Excellent,High,Medium
4,Canada,2013,Qtr 3,1,September,Paseo,Midmarket,31863.00,"12,9 €",24700.0,...,7163.00,22.480620,15,24700 €,2470,High,7163.00,Excellent,High,Medium

In [10]:
print(df.isnull().sum())

Country                 0
Year                    0
Quarter                 0
Day                     0
Month Name              0
Product                 0
Segment                 0
Sales                   0
Avg Sale per Unit       0
COGS                    0
Discounts               0
Gross Sales             0
Manufacturing Price     0
Month Number            0
Profit                  0
Profit Margin %         0
Sale Price              0
Total COGS              0
Units Sold              0
Discount Band          53
Profit Check            0
Performance             0
Profit Class            0
Profit Bin              0
dtype: int64

In [11]:
print(f"\nDuplicate rows: {df.duplicated().sum()}")

Duplicate rows: 0

In [12]:
print(df[df['Discount Band'].isnull()][['Segment', 'Product', 'Sales', 'Discount Band']].head(10))

             Segment    Product     Sales Discount Band
11        Enterprise    Montana   43125.0           NaN
16        Enterprise       Velo   43125.0           NaN
22        Government      Paseo  603750.0           NaN
31         Midmarket      Paseo   32280.0           NaN
35        Government  Carretera   32370.0           NaN
44        Government      Paseo    5840.0           NaN
47    Small Business        VTT  600300.0           NaN
72  Channel Partners    Montana   30216.0           NaN
74  Channel Partners      Paseo   30216.0           NaN
84        Enterprise    Montana  333187.5           NaN

In [13]:
null_discount = df[df['Discount Band'].isnull()]
print(null_discount['Discounts'].describe())
print(f"\nDiscounts = 0: {(null_discount['Discounts'] == 0).sum()}")
print(f"Discounts > 0: {(null_discount['Discounts'] > 0).sum()}")

count    53.0
mean      0.0
std       0.0
min       0.0
25%       0.0
50%       0.0
75%       0.0
max       0.0
Name: Discounts, dtype: float64

Discounts = 0: 53
Discounts > 0: 0

In [14]:
df['Discount Band'] = df['Discount Band'].fillna('None')

# Confirmar
print(df['Discount Band'].value_counts())
print(f"\nNulls remaining: {df['Discount Band'].isnull().sum()}")

Discount Band
High      241
Medium    234
Low       160
None       53
Name: count, dtype: int64

Nulls remaining: 0

In [15]:
print(df['Avg Sale per Unit'].head(10))
print(df['Total COGS'].head(10))

0    10,56 €
1      110 €
2      276 €
3     6,65 €
4     12,9 €
5     19,2 €
6      308 €
7    332,5 €
8     12,9 €
9    11,28 €
Name: Avg Sale per Unit, dtype: str
0      8283 €
1    289920 €
2    320750 €
3     11745 €
4     24700 €
5     26460 €
6    161980 €
7    319280 €
8     17430 €
9      6897 €
Name: Total COGS, dtype: str

In [16]:
# Limpar e converter Avg Sale per Unit
df['Avg Sale per Unit'] = (
    df['Avg Sale per Unit']
    .str.replace('€', '', regex=False)
    .str.replace(',', '.', regex=False)
    .str.strip()
    .astype(float)
)

# Limpar e converter Total COGS
df['Total COGS'] = (
    df['Total COGS']
    .str.replace('€', '', regex=False)
    .str.strip()
    .astype(float)
)

# Confirmar
print(df[['Avg Sale per Unit', 'Total COGS']].dtypes)
print(df[['Avg Sale per Unit', 'Total COGS']].head())

ValueError: could not convert string to float: '9733,5'

In [18]:
df['Total COGS'] = (
    df['Total COGS']
    .str.replace('€', '', regex=False)
    .str.replace(',', '.', regex=False)
    .str.strip()
    .astype(float)
)

print(df[['Avg Sale per Unit', 'Total COGS']].dtypes)
print(df[['Avg Sale per Unit', 'Total COGS']].head())

Avg Sale per Unit    float64
Total COGS           float64
dtype: object
   Avg Sale per Unit  Total COGS
0              10.56      8283.0
1             110.00    289920.0
2             276.00    320750.0
3               6.65     11745.0
4              12.90     24700.0

In [19]:
df.to_csv("financials_clean.csv", index=False)
print("Saved!")

Saved!

In [20]:
import pandas as pd
import numpy as np

df = pd.read_csv("financials_clean.csv")
df.head()

,Country,Year,Quarter,Day,Month Name,Product,Segment,Sales,Avg Sale per Unit,COGS,...,Profit,Profit Margin %,Sale Price,Total COGS,Units Sold,Discount Band,Profit Check,Performance,Profit Class,Profit Bin
0,Canada,2013,Qtr 3,1,September,Amarilla,Channel Partners,29156.16,10.56,8283.0,...,20873.16,71.590909,12,8283.0,2761,High,20873.16,Excellent,High,High
1,Canada,2013,Qtr 3,1,September,Carretera,Enterprise,265760.00,110.00,289920.0,...,-24160.00,-9.090909,125,289920.0,2416,High,-24160.00,Bad,Low,Low
2,Canada,2013,Qtr 3,1,September,Montana,Small Business,354108.00,276.00,320750.0,...,33358.00,9.420290,300,320750.0,1283,Medium,33358.00,Excellent,High,Very High
3,Canada,2013,Qtr 3,1,September,Paseo,Government,15620.85,6.65,11745.0,...,3875.85,24.812030,7,11745.0,2349,Medium,3875.85,Excellent,High,Medium
4,Canada,2013,Qtr 3,1,September,Paseo,Midmarket,31863.00,12.90,24700.0,...,7163.00,22.480620,15,24700.0,2470,High,7163.00,Excellent,High,Medium

In [21]:
df.shape()

TypeError: 'tuple' object is not callable

In [22]:
df.shape

(688, 24)

In [23]:
print(df['Segment'].head(10))

0    Channel Partners
1          Enterprise
2      Small Business
3          Government
4           Midmarket
5          Government
6          Government
7          Government
8           Midmarket
9    Channel Partners
Name: Segment, dtype: str

In [24]:
subset = df[['Segment', 'Country', 'Sales', 'Profit']]
print(subset.head())

            Segment Country      Sales    Profit
0  Channel Partners  Canada   29156.16  20873.16
1        Enterprise  Canada  265760.00 -24160.00
2    Small Business  Canada  354108.00  33358.00
3        Government  Canada   15620.85   3875.85
4         Midmarket  Canada   31863.00   7163.00

In [25]:
government = df[df['Segment'] == 'Government']
print(f"Government rows: {len(government)}")
print(government[['Country', 'Sales', 'Profit']].head())

Government rows: 288
   Country      Sales    Profit
3   Canada   15620.85   3875.85
5   Canada   50803.20  24343.20
6   Canada  191884.00  29904.00
7   Canada  408310.00  89030.00
10  Canada   19158.72   4903.72

In [26]:
gov_high = df[(df['Segment'] == 'Government') & (df['Sales'] > 1000000)]
print(f"Government + Sales > 1M: {len(gov_high)} rows")

Government + Sales > 1M: 3 rows

In [27]:
print(df.iloc[:3, :4])

  Country  Year Quarter  Day
0  Canada  2013   Qtr 3    1
1  Canada  2013   Qtr 3    1
2  Canada  2013   Qtr 3    1

In [28]:
print(df.loc[10:12, ['Segment', 'Country', 'Sales']])

       Segment Country     Sales
10  Government  Canada  19158.72
11  Enterprise  Canada  43125.00
12  Government  Canada  19158.72

In [29]:
top_sales = df.sort_values('Sales', ascending=False).head(10)
print(top_sales[['Segment', 'Country', 'Product', 'Sales', 'Profit']])

            Segment                   Country    Product      Sales    Profit
637      Government  United States of America      Paseo  1159200.0  262200.0
57   Small Business                    Canada    Montana  1038082.5   87457.5
87   Small Business                    Canada       Velo  1035625.5   87250.5
282      Government                   Germany   Amarilla  1017338.0  246178.0
293      Government                   Germany       Velo  1017338.0  246178.0
390      Government                   Germany       Velo   986811.0  238791.0
391      Government                   Germany        VTT   986811.0  238791.0
124      Government                    Canada  Carretera   978236.0  236716.0
129      Government                    Canada      Paseo   978236.0  236716.0
177      Government                    France   Amarilla   962500.0  247500.0

In [30]:
print(df[['Sales', 'Profit', 'Profit Margin %']].head())

       Sales    Profit  Profit Margin %
0   29156.16  20873.16        71.590909
1  265760.00 -24160.00        -9.090909
2  354108.00  33358.00         9.420290
3   15620.85   3875.85        24.812030
4   31863.00   7163.00        22.480620

In [31]:
df['Profit Margin %'] = round((df['Profit'] / df['Sales']) * 100, 2)
print(df[['Sales', 'Profit', 'Profit Margin %']].head())

       Sales    Profit  Profit Margin %
0   29156.16  20873.16            71.59
1  265760.00 -24160.00            -9.09
2  354108.00  33358.00             9.42
3   15620.85   3875.85            24.81
4   31863.00   7163.00            22.48

In [32]:
df['Profitable'] = np.where(df['Profit'] > 0, 'Yes', 'No')
print(df['Profitable'].value_counts())

Profitable
Yes    625
No      63
Name: count, dtype: int64

In [33]:
def classify_margin(margin):
    if margin > 20:
        return 'Excellent'
    elif margin > 10:
        return 'Good'
    elif margin > 0:
        return 'Low'
    else:
        return 'Loss'

df['Performance'] = df['Profit Margin %'].apply(classify_margin)
print(df['Performance'].value_counts())

Performance
Excellent    414
Good         123
Low           88
Loss          63
Name: count, dtype: int64

In [34]:
df['Revenue Category'] = pd.cut(
    df['Sales'],
    bins=[0, 50000, 100000, float('inf')],
    labels=['Low', 'Medium', 'High']
)
print(df['Revenue Category'].value_counts())

Revenue Category
Low       377
High      263
Medium     48
Name: count, dtype: int64

In [35]:
df.to_csv("financials_clean.csv", index=False)
print("Saved!")

Saved!